apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - mysql-secret.yaml
  - mysql-statefulset.yaml
  - mysql-service.yaml
images:
  - name: ghcr.io/dewgenenny/endolla-watcher-backend
    newName: ghcr.io/dewgenenny/endolla-watcher-backend
    newTag: 0d9ef8727710ffd52b863b76746f392f89356335
  - name: ghcr.io/dewgenenny/endolla-watcher-frontend
    newName: ghcr.io/dewgenenny/endolla-watcher-frontend
    newTag: 0d9ef8727710ffd52b863b76746f392f89356335
commonLabels:
  app.kubernetes.io/part-of: endolla-watcher
